//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Portfolio.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [Display(Name = "Imiê")]
        [DataType(DataType.Text)]
        public string Name { get; set; }


        [Display(Name = "Nazwisko")]
        [DataType(DataType.Text)]
        public string Surname { get; set; }

        [Display(Name = "NAdres Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Display(Name = "Adres")]
        [DataType(DataType.Text)]
        public string Adress { get; set; }

        [Display(Name = "Opis")]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [Display(Name = "Numer telefonu")]
        [DataType(DataType.Text)]
        public string PhoneNumber { get; set; }

        [Display(Name = "Nazwa firmy")]
        [DataType(DataType.Text)]
        public string CompanyName { get; set; }
    }
}
